// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestDeIa.Infrastructure.Persistence;

#nullable disable

namespace TestDeIa.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TestDeIaDbContext))]
    [Migration("20260626032541_AddProductoControlaStock")]
    partial class AddProductoControlaStock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.CatalogoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Catalogos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            Codigo = "TIPO_IDENTIFICACION",
                            Descripcion = "Tipos base de identificacion para personas y clientes.",
                            IsActive = true,
                            Nombre = "Tipo de identificacion"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            Codigo = "ESTADO_CIVIL",
                            Descripcion = "Estado civil de personas.",
                            IsActive = true,
                            Nombre = "Estado civil"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            Codigo = "ESTADO_REGISTRO",
                            Descripcion = "Estados funcionales de registros activos e inactivos.",
                            IsActive = true,
                            Nombre = "Estado de registro"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000004"),
                            Codigo = "ESTADO_DOCUMENTO_ELECTRONICO",
                            Descripcion = "Estados de comprobantes electronicos.",
                            IsActive = true,
                            Nombre = "Estado documento electronico"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000005"),
                            Codigo = "AMBIENTE_SRI",
                            Descripcion = "Ambiente de emision para comprobantes electronicos.",
                            IsActive = true,
                            Nombre = "Ambiente SRI"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000006"),
                            Codigo = "TIPO_EMISION",
                            Descripcion = "Tipo de emision de documentos electronicos.",
                            IsActive = true,
                            Nombre = "Tipo de emision"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000007"),
                            Codigo = "FORMA_PAGO_SRI",
                            Descripcion = "Formas de pago segun catalogo del SRI.",
                            IsActive = true,
                            Nombre = "Forma de pago SRI"
                        });
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.CatalogoItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatalogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoId", "Codigo")
                        .IsUnique();

                    b.ToTable("CatalogoItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000001"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000001"),
                            Codigo = "RUC",
                            IsActive = true,
                            Nombre = "RUC",
                            Orden = 1
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000002"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000001"),
                            Codigo = "Cedula",
                            IsActive = true,
                            Nombre = "Cedula",
                            Orden = 2
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000003"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000001"),
                            Codigo = "Pasaporte",
                            IsActive = true,
                            Nombre = "Pasaporte",
                            Orden = 3
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000004"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000001"),
                            Codigo = "Consumidor Final",
                            IsActive = true,
                            Nombre = "Consumidor final",
                            Orden = 4
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000005"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000001"),
                            Codigo = "Identificacion del Exterior",
                            IsActive = true,
                            Nombre = "Identificacion del exterior",
                            Orden = 5
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000006"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000001"),
                            Codigo = "Placa",
                            IsActive = true,
                            Nombre = "Placa",
                            Orden = 6
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000011"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000002"),
                            Codigo = "SOLTERO",
                            IsActive = true,
                            Nombre = "Soltero",
                            Orden = 1
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000012"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000002"),
                            Codigo = "CASADO",
                            IsActive = true,
                            Nombre = "Casado",
                            Orden = 2
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000013"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000002"),
                            Codigo = "DIVORCIADO",
                            IsActive = true,
                            Nombre = "Divorciado",
                            Orden = 3
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000014"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000002"),
                            Codigo = "VIUDO",
                            IsActive = true,
                            Nombre = "Viudo",
                            Orden = 4
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000015"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000002"),
                            Codigo = "UNION_LIBRE",
                            IsActive = true,
                            Nombre = "Union libre",
                            Orden = 5
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000021"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000003"),
                            Codigo = "ACTIVO",
                            IsActive = true,
                            Nombre = "Activo",
                            Orden = 1
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000022"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000003"),
                            Codigo = "INACTIVO",
                            IsActive = true,
                            Nombre = "Inactivo",
                            Orden = 2
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000031"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000004"),
                            Codigo = "Pendiente",
                            IsActive = true,
                            Nombre = "Pendiente",
                            Orden = 1
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000032"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000004"),
                            Codigo = "EnProceso",
                            IsActive = true,
                            Nombre = "En proceso",
                            Orden = 2
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000033"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000004"),
                            Codigo = "Recibido",
                            IsActive = true,
                            Nombre = "Recibido",
                            Orden = 3
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000034"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000004"),
                            Codigo = "Autorizado",
                            IsActive = true,
                            Nombre = "Autorizado",
                            Orden = 4
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000035"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000004"),
                            Codigo = "Rechazado",
                            IsActive = true,
                            Nombre = "Rechazado",
                            Orden = 5
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000036"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000004"),
                            Codigo = "Error",
                            IsActive = true,
                            Nombre = "Error",
                            Orden = 6
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000041"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000005"),
                            Codigo = "Pruebas",
                            Descripcion = "Codigo SRI 1",
                            IsActive = true,
                            Nombre = "Pruebas",
                            Orden = 1
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000042"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000005"),
                            Codigo = "Produccion",
                            Descripcion = "Codigo SRI 2",
                            IsActive = true,
                            Nombre = "Produccion",
                            Orden = 2
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000051"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000006"),
                            Codigo = "Normal",
                            Descripcion = "Codigo SRI 1",
                            IsActive = true,
                            Nombre = "Normal",
                            Orden = 1
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000061"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000007"),
                            Codigo = "Efectivo",
                            Descripcion = "Codigo SRI 01",
                            IsActive = true,
                            Nombre = "Efectivo",
                            Orden = 1
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000062"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000007"),
                            Codigo = "Compensacion",
                            Descripcion = "Codigo SRI 15",
                            IsActive = true,
                            Nombre = "Compensacion",
                            Orden = 2
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000063"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000007"),
                            Codigo = "Tarjeta de debito",
                            Descripcion = "Codigo SRI 16",
                            IsActive = true,
                            Nombre = "Tarjeta de debito",
                            Orden = 3
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000064"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000007"),
                            Codigo = "Dinero electronico",
                            Descripcion = "Codigo SRI 17",
                            IsActive = true,
                            Nombre = "Dinero electronico",
                            Orden = 4
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000065"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000007"),
                            Codigo = "Tarjeta prepago",
                            Descripcion = "Codigo SRI 18",
                            IsActive = true,
                            Nombre = "Tarjeta prepago",
                            Orden = 5
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000066"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000007"),
                            Codigo = "Tarjeta de credito",
                            Descripcion = "Codigo SRI 19",
                            IsActive = true,
                            Nombre = "Tarjeta de credito",
                            Orden = 6
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000067"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000007"),
                            Codigo = "Transferencia",
                            Descripcion = "Codigo SRI 20",
                            IsActive = true,
                            Nombre = "Transferencia",
                            Orden = 7
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000068"),
                            CatalogoId = new Guid("70000000-0000-0000-0000-000000000007"),
                            Codigo = "Endoso de titulos",
                            Descripcion = "Codigo SRI 21",
                            IsActive = true,
                            Nombre = "Endoso de titulos",
                            Orden = 8
                        });
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.ClienteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "PersonaId")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.EmpleadoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "PersonaId")
                        .IsUnique();

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.EmpresaEmisoraEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgenteRetencionResolucion")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("AmbienteSri")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CertificadoClave")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("CertificadoContenido")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CertificadoNombreArchivo")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ContribuyenteEspecial")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DireccionEstablecimiento")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DireccionMatriz")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Establecimiento")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("LogoRideContenido")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LogoRideMimeType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("ModoDesarrollo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("ObligadoContabilidad")
                        .HasColumnType("bit");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PuntoEmision")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RegimenRimpe")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("TipoEmision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Ruc")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "Ruc")
                        .IsUnique();

                    b.ToTable("EmpresasEmisoras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AmbienteSri = "Pruebas",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DireccionEstablecimiento = "Sucursal demo",
                            DireccionMatriz = "Matriz demo",
                            Establecimiento = "001",
                            IsActive = true,
                            ModoDesarrollo = true,
                            NombreComercial = "EasyMarket Demo",
                            ObligadoContabilidad = false,
                            OwnerUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PuntoEmision = "001",
                            RazonSocial = "EasyMarket Demo S.A.",
                            Ruc = "0999999999001",
                            TipoEmision = "Normal"
                        });
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.FacturaDetalleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CodigoIva")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("IvaValor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("PorcentajeIva")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("FacturaDetalles", (string)null);
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.FacturaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgenteRetencionResolucion")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("AmbienteSri")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClaveAcceso")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.Property<string>("ClienteDireccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ClienteEmail")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClienteIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ClienteTelefono")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ClienteTipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ContribuyenteEspecial")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DireccionEstablecimientoEmisor")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DireccionMatrizEmisor")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("EmpresaEmisoraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Establecimiento")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset?>("FechaAutorizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaEmision")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("FormaPagoSriCodigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("InventarioAplicado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("InventarioAplicadoAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("IvaTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MensajeEstado")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreComercialEmisor")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NumeroAutorizacion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("ObligadoContabilidad")
                        .HasColumnType("bit");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ProcessingNode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PuntoEmision")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("RazonSocialEmisor")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RegimenRimpe")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("RucEmisor")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<long>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Secuencial"));

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubtotalIva0")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubtotalIva15")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubtotalIva5")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubtotalIva8")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoEmision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDescuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("XmlFirmado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XmlGenerado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClaveAcceso")
                        .IsUnique();

                    b.HasIndex("Estado", "CreatedAt");

                    b.HasIndex("Establecimiento", "PuntoEmision", "Secuencial")
                        .IsUnique();

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.FacturaSriEventoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId", "CreatedAt");

                    b.ToTable("FacturaSriEventos", (string)null);
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.KardexMovimientoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadEntrada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CantidadSalida")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("CostoPromedio")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaMovimiento")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Referencia")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("SaldoCantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SaldoValor")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId", "FechaMovimiento");

                    b.ToTable("KardexMovimientos", (string)null);
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.PersonaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Identificacion")
                        .IsUnique();

                    b.ToTable("Personas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Apellidos = "Sistema",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@testdeia.local",
                            EmpresaId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Identificacion = "ADMIN",
                            IsActive = true,
                            IsSystemRecord = true,
                            Nombres = "Administrador",
                            TipoIdentificacion = "Sistema"
                        });
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.ProductoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CodigoIva")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("ControlaStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("CostoPromedio")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("PorcentajeIva")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("StockActual")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique();

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.SecurityRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("SecurityRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        });
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.SecurityUserEmpresaEntity", b =>
                {
                    b.Property<Guid>("SecurityUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.HasKey("SecurityUserId", "EmpresaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("SecurityUserEmpresas", (string)null);

                    b.HasData(
                        new
                        {
                            SecurityUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EmpresaId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDefault = true
                        });
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.SecurityUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "NormalizedUserName")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "PersonaId")
                        .IsUnique();

                    b.ToTable("SecurityUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Administrador",
                            Email = "admin@testdeia.local",
                            EmpresaId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            NormalizedEmail = "ADMIN@TESTDEIA.LOCAL",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "0A5BC3E342432F1BAD92FFD51B785343EC72906CDBA6A26131060B008E786656",
                            PersonaId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.SecurityUserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("SecurityUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.CatalogoItemEntity", b =>
                {
                    b.HasOne("TestDeIa.Infrastructure.Persistence.Entities.CatalogoEntity", "Catalogo")
                        .WithMany("Items")
                        .HasForeignKey("CatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalogo");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.ClienteEntity", b =>
                {
                    b.HasOne("TestDeIa.Infrastructure.Persistence.Entities.PersonaEntity", "Persona")
                        .WithOne("Cliente")
                        .HasForeignKey("TestDeIa.Infrastructure.Persistence.Entities.ClienteEntity", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.EmpleadoEntity", b =>
                {
                    b.HasOne("TestDeIa.Infrastructure.Persistence.Entities.PersonaEntity", "Persona")
                        .WithOne("Empleado")
                        .HasForeignKey("TestDeIa.Infrastructure.Persistence.Entities.EmpleadoEntity", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.FacturaDetalleEntity", b =>
                {
                    b.HasOne("TestDeIa.Infrastructure.Persistence.Entities.FacturaEntity", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.FacturaSriEventoEntity", b =>
                {
                    b.HasOne("TestDeIa.Infrastructure.Persistence.Entities.FacturaEntity", "Factura")
                        .WithMany("EventosSri")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.KardexMovimientoEntity", b =>
                {
                    b.HasOne("TestDeIa.Infrastructure.Persistence.Entities.ProductoEntity", "Producto")
                        .WithMany("KardexMovimientos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.SecurityUserEmpresaEntity", b =>
                {
                    b.HasOne("TestDeIa.Infrastructure.Persistence.Entities.EmpresaEmisoraEntity", "Empresa")
                        .WithMany("UserAssignments")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestDeIa.Infrastructure.Persistence.Entities.SecurityUserEntity", "SecurityUser")
                        .WithMany("EmpresasAcceso")
                        .HasForeignKey("SecurityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("SecurityUser");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.SecurityUserEntity", b =>
                {
                    b.HasOne("TestDeIa.Infrastructure.Persistence.Entities.PersonaEntity", "Persona")
                        .WithOne("SecurityUser")
                        .HasForeignKey("TestDeIa.Infrastructure.Persistence.Entities.SecurityUserEntity", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.SecurityUserRoleEntity", b =>
                {
                    b.HasOne("TestDeIa.Infrastructure.Persistence.Entities.SecurityRoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestDeIa.Infrastructure.Persistence.Entities.SecurityUserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.CatalogoEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.EmpresaEmisoraEntity", b =>
                {
                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.FacturaEntity", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("EventosSri");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.PersonaEntity", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("SecurityUser");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.ProductoEntity", b =>
                {
                    b.Navigation("KardexMovimientos");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.SecurityRoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TestDeIa.Infrastructure.Persistence.Entities.SecurityUserEntity", b =>
                {
                    b.Navigation("EmpresasAcceso");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
