<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>06969c1a-e825-4f9e-882a-45551a623d87</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ReportViewerCore.NETCore" Version="15.1.33" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestDeIa.Application\TestDeIa.Application.csproj" />
    <ProjectReference Include="..\TestDeIa.Infrastructure\TestDeIa.Infrastructure.csproj" />
    <ProjectReference Include="..\TestDeIa.Shared\TestDeIa.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Reporting\Templates\FacturaRide.rdlc" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Reporting\Templates\SriFacturaBanner.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
